### ISSUE TITLE
HTTP_PROXY / HTTPS_PROXY settings ignored, unable to use bastion tunnels.

### ISSUE THREAD

**Issue by gtfortytwo** [citrix/adc-nitro-go#7]
I discovered when attempting to use the [Citrix ADC terraform provider](https://github.com/citrix/terraform-provider-citrixadc) that the environment proxy settings seem to be ignored (citrix/terraform-provider-citrixadc#254).  Digging further, it seems that terraform provider uses this `adc-nitro-go` library as its underlying client, and the root of the problem lies here.

This broken/absent proxy support makes the TF provider (and this library) practically unusable for us because our ADC management interfaces are nearly always on protected networks which require the use of a jump/bastion host to reach them.

AFAICT this `adc-nitro-go` lib uses the native [golang http packages](https://golang.org/src/net/http/transport.go) as its client library which, by default, will respect and use proxy settings defined in the environment (when using the default `Transport`). One actually has to configure away that functionality by customizing the `Transport` to disable it.  In [this block of code](https://github.com/citrix/adc-nitro-go/blob/a57db5c1f504b9db84b4657cf54e8199aefe1350/service/client.go#L99-L124) if you just added a `Proxy: http.ProxyFromEnvironment` parameter to each Transport creation I _believe_ that would restore the built-in proxy support.
```golang
if params.SslVerify {
  if len(params.RootCAPath) > 0 {
    caCert, err := ioutil.ReadFile(params.RootCAPath)
    if err != nil {
      return nil, fmt.Errorf("Unable to read certificate file: %v", err)
    }
    caCertPool := x509.NewCertPool()
    if ok := caCertPool.AppendCertsFromPEM(caCert); !ok {
      return nil, fmt.Errorf("Could not Append CA certificate.")
    }
    tr := &http.Transport{
      TLSClientConfig: &tls.Config{
        RootCAs:    caCertPool,
        ServerName: params.ServerName,
      },
    }
    c.client = &http.Client{Transport: tr}
  } else {
    c.client = &http.Client{}
  }
} else {
  tr := &http.Transport{
    TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
  }
  c.client = &http.Client{Transport: tr}
}
```

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #11
